[package]
name = "inu-rs"
version = "0.1.0"
authors = ["Piet Geursen <pietgeursen@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3.8"
uuid = {version = "0.8.1", features = ["v4"]}

[dev-dependencies]
async-std = {version = "1.7.0", features = ["unstable"]}
